
CREATE TRIGGER User_TypesCHeck BEFORE INSERT ON USER_TYPES
       FOR EACH ROW SET new.active=TRUE;

CREATE TRIGGER User_STATUSCHeck BEFORE INSERT ON USER_STATUS
       FOR EACH ROW SET new.active=TRUE;