use NOTICIERO_WEB;

CREATE TABLE IF NOT EXISTS LIKES(
ID_LIKE INT NOT NULL AUTO_INCREMENT PRIMARY KEY comment "Llave primaria e identificador ddel like",
ID_USER INT NOT NULL COMMENT "USUARIO QUE DIO EL LIKE",
FOREIGN KEY(ID_USER) REFERENCES USUARIO(ID_user),
ID_NEWS INT NOT NULL COMMENT "POST AL QUE SE LE DIO LIKE",
FOREIGN KEY(ID_NEWS) REFERENCES NOTICIAS(ID_Noticia),
ACTIVE BOOLEAN NOT NULL COMMENT "Estado activo del like"
);

select * from likes;